server:
  port: 8180
  
spring:
  application:
    name: banking-customer-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    url: jdbc:mariadb://localhost:3306/bankcustomer
    username: root 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    